server:
  port: 8084
spring:
  application:
    name: gobangsocket
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # nacos服务器地址
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/togo_gobang?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver